identity_card_type_list:
  path: /list/{pageLabel}-{page}/{orderLabel}-{order}-{orderBy}/{limitLabel}-{limit}/{filters}
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypeGetController, pageLabel: 'page' , page: 1 , orderLabel: 'order' , order: 'createAt' , orderBy: 'desc' , limitLabel: 'rows_per_page' , limit: 10 , filters: null }
  methods:  [GET,POST]

identity_card_type_add:
  path: /create
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypeAddController}
  methods:  [GET]

identity_card_type_create:
  path: /create
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypePostController}
  methods:  [POST]

identity_card_type_edit:
  path: /edit/{id}
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypeEditController}
  methods:  [GET]

identity_card_type_update:
  path: /update
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypePutController}
  methods:  [POST]

identity_card_type_description_available:
  path: /description-available
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypeDescriptionAvailabilityController }
  methods:  [GET]

identity_card_type_delete:
  path: /delete
  defaults: { _controller: App\Backoffice\IdentityCardType\Infrastructure\UserInterface\Web\IdentityCardTypeDeleteController}
  methods:  [POST]
