forgot_password_request:
  path: /reset-password
  defaults: { _controller: App\ResetPasswordRequest\Infrastructure\UserInterface\Web\ResetPasswordRequestController}
  methods:  [GET]

process_sending_password_reset_email:
  path: /reset-password
  defaults: { _controller: App\ResetPasswordRequest\Infrastructure\UserInterface\Web\ProcessSendingPasswordResetEmailController}
  methods:  [POST]


email_message_sent:
  path: /email-message-sent
  defaults: { _controller: App\ResetPasswordRequest\Infrastructure\UserInterface\Web\EmailMessageSentController}
  methods:  [GET,POST]

reset_password:
  path: /set-a-new-password/{token}
  defaults: { _controller: App\ResetPasswordRequest\Infrastructure\UserInterface\Web\NewPasswordGetController,token: null}
  methods:  [GET]

update_password:
  path: /set-a-new-password
  defaults: { _controller: App\ResetPasswordRequest\Infrastructure\UserInterface\Web\NewPasswordPostController,token: null}
  methods:  [POST]