<?php

declare(strict_types=1);

namespace App\Tests\Backoffice\TrafficPoliceBooth\Infrastructure\Persistence;

use App\Shared\Domain\ValueObject\Uuid;
use App\Tests\Backoffice\TrafficPoliceBooth\Domain\TrafficPoliceBoothMother;
use App\Backoffice\TrafficPoliceBooth\Domain\TrafficPoliceBooth;
use App\Tests\Backoffice\TrafficPoliceBooth\TrafficPoliceBoothInfrastructureTestCase;
use App\Tests\Shared\Domain\Criteria\CriteriaMother;


final class MySqlTrafficPoliceBoothRepositoryTest extends TrafficPoliceBoothInfrastructureTestCase
{
	private TrafficPoliceBooth $trafficPoliceBooth;

	private Uuid $id;
	
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		
		$this->trafficPoliceBooth =  TrafficPoliceBoothMother::random();
		
		$this->id = new Uuid($this->trafficPoliceBooth->getId());
	}
	
	/** @test */
	public function it_should_save_a_traffic_police_booth(): void
    {
	    $this->repository()->save($this->trafficPoliceBooth);
	    
	    $this->clearUnitOfWork();
	    
	    $this->assertNotNull($this->repository()->search($this->id));
    }

    /** @test */
    public function it_should_return_an_existing_traffic_police_booth(): void
    {
        $this->repository()->save($this->trafficPoliceBooth);
	
	    $this->clearUnitOfWork();
	
	    $itemFound = $this->repository()->search($this->id);
	
	    $this->assertNull(
	        $this->assertSimilar($this->trafficPoliceBooth,$itemFound)
	    );
    }

    /** @test */
    public function it_should_not_return_a_non_existing_traffic_police_booth(): void
    {
        $this->assertNull(
        	$this->repository()->search($this->id)
        );
    }
	
	/** @test */
    public function it_should_delete_an_existing_author()
    {
	    $this->repository()->save($this->trafficPoliceBooth);
	    
	    $this->clearUnitOfWork();
	
	    $itemFound = $this->repository()->search($this->id);
	
	    $this->assertNull(
	    	$this->repository()->delete($itemFound)
	    );
    }
	
	
	/** @test */
	public function it_should_search_all_existing_author(): void
	{
		$existingAuthor        = TrafficPoliceBoothMother::random();
		$anotherExistingAuthor = TrafficPoliceBoothMother::random();
		$existingAuthors       = [$existingAuthor, $anotherExistingAuthor];
		
		$this->repository()->save($existingAuthor);
		$this->repository()->save($anotherExistingAuthor);
		$this->clearUnitOfWork();
		
		$this->assertEquals(
			count($existingAuthors),
			count($this->repository()->searchAll())
		);
	}
	
	/** @test */
	public function it_should_search_all_existing_authors_with_an_empty_criteria(): void
	{
		$existingItem        = TrafficPoliceBoothMother::random();
		$anotherExistingItem = TrafficPoliceBoothMother::random();
		$existingItems       = [$existingItem, $anotherExistingItem];
		
		$this->repository()->save($existingItem);
		$this->repository()->save($anotherExistingItem);
		$this->clearUnitOfWork();
		
		$this->assertEquals(
			count($existingItems),
			count($this->repository()->matching(CriteriaMother::empty()))
		);
	}
	
	/** @test */
	public function it_should_filter_by_criteria(): void
	{
		$dddInPhpItem  = TrafficPoliceBoothMother::randomWithDescription('DDD en PHP');
		$dddInJavaItem = TrafficPoliceBoothMother::randomWithDescription('DDD en Java');
		$intellijItem  = TrafficPoliceBoothMother::randomWithDescription('Exprimiendo Intellij');
		$dddAuthors   = [$dddInPhpItem, $dddInJavaItem];
		
		$fullNameContainsDddCriteria = CriteriaMother::contains('description','DDD');
		
		$this->repository()->save($dddInJavaItem);
		$this->repository()->save($dddInPhpItem);
		$this->repository()->save($intellijItem);
		$this->clearUnitOfWork();
		
		$this->assertEquals(
			count($dddAuthors),
			count($this->repository()->matching($fullNameContainsDddCriteria))
		);
		
	}
	
	
}
