<?php
	
	
	namespace App\Tests\Backoffice\TrafficPoliceBooth\Infrastructure\UserInterface\Web;
	
	use App\Backoffice\TrafficPoliceBooth\Domain\TrafficPoliceBooth;
	use App\Backoffice\TrafficPoliceBooth\Domain\TagRepository;
	use App\Shared\Domain\ValueObject\Uuid;
	use App\Tests\Backoffice\TrafficPoliceBooth\Domain\TrafficPoliceBoothMother;
	use App\Tests\Backoffice\TrafficPoliceBooth\TrafficPoliceBoothInfrastructureTestCase;
	
	final class TrafficPoliceBoothEditControllerTest extends TrafficPoliceBoothInfrastructureTestCase
	{
		private TrafficPoliceBooth $trafficPoliceBooth;
		
		private Uuid $id;
		
		/** @test
		 * Comprueba que se cargue corretamente la interfaz para editar un registro y el funcionamiento de controlador
		 * encargado de actualizar la información.
		 */
		public function it_should_update_a_traffic_police_booth()
		{
			$this->repository()->save($this->trafficPoliceBooth);
			
			$client = static::createClient();
			
			$crawler = $client->request('GET', self::EDIT_ITEM_PATH .'/'. $this->trafficPoliceBooth->getId());
			
			$form = $crawler->selectButton('submit')->form();
			
			$form['description'] = $this->trafficPoliceBooth->getDescription();
			
			$form['id'] = $this->trafficPoliceBooth->getId();
			
			$client->submit($form);
			
			$this->assertTrue(
				$client->getResponse()->isRedirect(self::LIST_ITEMS_PATH)
			);
			
		}
		
		protected function setUp(): void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
			
			$this->trafficPoliceBooth = TrafficPoliceBoothMother::random();
			
			$this->id = new Uuid($this->trafficPoliceBooth->getId());
		}
	}