reason_for_trip_list:
  path: /list/{pageLabel}-{page}/{orderLabel}-{order}-{orderBy}/{limitLabel}-{limit}/{filters}
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripGetController, pageLabel: 'page' , page: 1 , orderLabel: 'order' , order: 'createAt' , orderBy: 'desc' , limitLabel: 'rows_per_page' , limit: 10 , filters: null }
  methods:  [GET,POST]

reason_for_trip_add:
  path: /create
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripAddController}
  methods:  [GET]

reason_for_trip_create:
  path: /create
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripPostController}
  methods:  [POST]

reason_for_trip_edit:
  path: /edit/{id}
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripEditController}
  methods:  [GET]

reason_for_trip_update:
  path: /update
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripPutController}
  methods:  [POST]

reason_for_trip_description_available:
  path: /description-available
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripDescriptionAvailableController}
  methods:  [GET]

reason_for_trip_delete:
  path: /delete
  defaults: { _controller: App\Backoffice\ReasonForTrip\Infrastructure\UserInterface\Web\ReasonForTripDeleteController}
  methods:  [POST]
