<?php
	
	
	namespace App\Tests\Backoffice\User\Infrastructure\UserInterface\Web;
	
	
	
	use App\Tests\Backoffice\User\UserInfrastructureTestCase;
	
	final class UserEditControllerTest extends UserInfrastructureTestCase
	{
		private  $user;
		
		/** @test
		 * Comprueba que se cargue corretamente la interfaz para editar un registro y el funcionamiento de controlador
		 * encargado de actualizar la información.
		 */
		public function it_should_update_a_user()
		{
			$client = static::createClient();
			
			$crawler = $client->request('GET', self::EDIT_ITEM_PATH .'/'. $this->user->getId());
			
			$form = $crawler->selectButton('submit')->form();
			
			$form['id'] = $this->user->getId();
			$form['name'] = $this->user->getName();
			$form['surname'] = $this->user->getSurname();
			$form['email'] = $this->user->getEmail() ;
			$form['role_id'] = $this->user->getrole()->getId() ;
			$form['isActive'] = 'on';
			$form['trafficPoliceBooth_id'] = $this->user->gettrafficPoliceBooth()->getId() ;
			
			$client->submit($form);
			
			$this->assertTrue(
				$client->getResponse()->isRedirect(self::LIST_ITEMS_PATH)
			);
			
		}
		
		protected function setUp(): void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
			
			$this->user = $this->getUserCreatedForTest();
			
			$this->repository()->save($this->user);
		}
	}